apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  destination:
    namespace: nginx-test
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: app
    repoURL: https://github.com/morbereus/argocd-test.git
    targetRevision: minikube
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
